// GENERATED by scripts/bump-version.ps1 -- do not edit.
// Source of truth is version in shell-tauri/tauri.conf.json. Committed (not gitignored) so a
// fresh clone can 'bun run dev' and typecheck without running the bump script first.
export const APP_VERSION = "0.1.5";
