# Bumps the app version and propagates it into the generated core/src/version.ts.
#
#   .\scripts\bump-version.ps1 patch          # 0.1.0 -> 0.1.1
#   .\scripts\bump-version.ps1 minor          # 0.1.3 -> 0.2.0
#   .\scripts\bump-version.ps1 major          # 0.2.7 -> 1.0.0
#   .\scripts\bump-version.ps1 -Version 1.2.3 # explicit
#   .\scripts\bump-version.ps1 patch -WhatIf  # print the transition, write nothing
#
# shell-tauri/tauri.conf.json is the single source of truth: it is what the Tauri build and the
# installer read (scripts/package-win.ps1). shell-tauri/Cargo.toml carries the same version (it
# feeds the exe's file-version metadata), so both are rewritten together; core/src/version.ts is
# generated. There is never a second version to forget.
#
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads .ps1 as ANSI, so a UTF-8 em-dash
# or curly quote in a comment corrupts the parse of the whole script.
#
# Emits the new version as the only stdout line, so callers can capture it:
#   $version = & .\scripts\bump-version.ps1 patch

[CmdletBinding(SupportsShouldProcess)]
param(
  [Parameter(Position = 0)]
  [ValidateSet("patch", "minor", "major")]
  [string]$Part = "patch",

  # Explicit version, overriding $Part. Bare semver (x.y.z), no leading "v".
  [ValidatePattern('^\d+\.\d+\.\d+$')]
  [string]$Version
)

$ErrorActionPreference = "Stop"
$repo = Split-Path -Parent $PSScriptRoot
$confPath = Join-Path $repo "shell-tauri\tauri.conf.json"
$cargoPath = Join-Path $repo "shell-tauri\Cargo.toml"
$versionTsPath = Join-Path $repo "core\src\version.ts"

# The "version" line of tauri.conf.json / the version line of Cargo.toml [package]. Line-targeted
# regex replacement, not parse-and-reserialize, so formatting and key order never churn.
$confLine = '(?m)^(\s*"version":\s*")([^"]+)(",?\s*)$'
$cargoLine = '(?m)^(version\s*=\s*")([^"]+)(")'

# --- read current ---
# ReadAllText, NOT Get-Content -Raw: under Windows PowerShell 5.1 Get-Content decodes as ANSI and
# a non-ASCII byte anywhere would mojibake on the UTF-8 write-back.
$conf = [System.IO.File]::ReadAllText($confPath)
if ($conf -notmatch $confLine) { throw "Could not find version in $confPath" }
$current = $Matches[2]
if ($current -notmatch '^\d+\.\d+\.\d+$') {
  throw "Current version '$current' in $confPath is not bare semver (x.y.z)"
}
$cargo = [System.IO.File]::ReadAllText($cargoPath)
if ($cargo -notmatch $cargoLine) { throw "Could not find version in $cargoPath" }

# --- compute next ---
if ($Version) {
  $next = $Version
} else {
  $n = $current.Split(".") | ForEach-Object { [int]$_ }
  switch ($Part) {
    "major" { $next = "$($n[0] + 1).0.0" }
    "minor" { $next = "$($n[0]).$($n[1] + 1).0" }
    "patch" { $next = "$($n[0]).$($n[1]).$($n[2] + 1)" }
  }
}

if ($next -eq $current) { throw "New version equals current version ($current); nothing to do" }
Write-Host "$current -> $next" -ForegroundColor Cyan

# --- write ---
$updatedConf = [regex]::Replace($conf, $confLine, { param($m) "$($m.Groups[1].Value)$next$($m.Groups[3].Value)" }, 1)
$updatedCargo = [regex]::Replace($cargo, $cargoLine, { param($m) "$($m.Groups[1].Value)$next$($m.Groups[3].Value)" }, 1)

$versionTs = @"
// GENERATED by scripts/bump-version.ps1 -- do not edit.
// Source of truth is version in shell-tauri/tauri.conf.json. Committed (not gitignored) so a
// fresh clone can 'bun run dev' and typecheck without running the bump script first.
export const APP_VERSION = "$next";
"@

if ($PSCmdlet.ShouldProcess("$confPath, $cargoPath and $versionTsPath", "write version $next")) {
  # UTF8Encoding($false) = no BOM; a BOM would break the JSON/TOML parsers. Only the version lines
  # change, so line endings are preserved as found.
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($confPath, $updatedConf, $utf8NoBom)
  [System.IO.File]::WriteAllText($cargoPath, $updatedCargo, $utf8NoBom)
  [System.IO.File]::WriteAllText($versionTsPath, ($versionTs -replace "`r`n", "`n") + "`n", $utf8NoBom)
  Write-Host "  updated shell-tauri\tauri.conf.json" -ForegroundColor DarkGray
  Write-Host "  updated shell-tauri\Cargo.toml" -ForegroundColor DarkGray
  Write-Host "  wrote   core\src\version.ts" -ForegroundColor DarkGray
} else {
  Write-Host "  (WhatIf) no files written" -ForegroundColor DarkGray
}

# The one stdout line, for: $v = & .\scripts\bump-version.ps1 patch
$next
