# Bumps the app version and propagates it into the generated core/src/version.ts.
#
#   .\scripts\bump-version.ps1 patch          # 0.1.0 -> 0.1.1
#   .\scripts\bump-version.ps1 minor          # 0.1.3 -> 0.2.0
#   .\scripts\bump-version.ps1 major          # 0.2.7 -> 1.0.0
#   .\scripts\bump-version.ps1 -Version 1.2.3 # explicit
#   .\scripts\bump-version.ps1 patch -WhatIf  # print the transition, write nothing
#
# shell/electrobun.config.ts is the single source of truth: it is what the Electrobun bundle and
# the installer already read (scripts/package-win.ps1). Everything else is generated from it, so
# there is never a second version to forget.
#
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads .ps1 as ANSI, so a UTF-8 em-dash
# or curly quote in a comment corrupts the parse of the whole script.
#
# Emits the new version as the only stdout line, so callers can capture it:
#   $version = & .\scripts\bump-version.ps1 patch

[CmdletBinding(SupportsShouldProcess)]
param(
  [Parameter(Position = 0)]
  [ValidateSet("patch", "minor", "major")]
  [string]$Part = "patch",

  # Explicit version, overriding $Part. Bare semver (x.y.z), no leading "v".
  [ValidatePattern('^\d+\.\d+\.\d+$')]
  [string]$Version
)

$ErrorActionPreference = "Stop"
$repo = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repo "shell\electrobun.config.ts"
$versionTsPath = Join-Path $repo "core\src\version.ts"

$versionLine = '(?m)^(\s*version:\s*")([^"]+)(",?\s*)$'

# --- read current ---
# ReadAllText, NOT Get-Content -Raw: under Windows PowerShell 5.1 Get-Content decodes as ANSI, and
# electrobun.config.ts has non-ASCII (em-dashes, arrows) in its comments. Reading ANSI and writing
# back UTF-8 silently mojibakes every one of them.
$config = [System.IO.File]::ReadAllText($configPath)
if ($config -notmatch $versionLine) { throw "Could not find app.version in $configPath" }
$current = $Matches[2]
if ($current -notmatch '^\d+\.\d+\.\d+$') {
  throw "Current version '$current' in $configPath is not bare semver (x.y.z)"
}

# --- compute next ---
if ($Version) {
  $next = $Version
} else {
  $n = $current.Split(".") | ForEach-Object { [int]$_ }
  switch ($Part) {
    "major" { $next = "$($n[0] + 1).0.0" }
    "minor" { $next = "$($n[0]).$($n[1] + 1).0" }
    "patch" { $next = "$($n[0]).$($n[1]).$($n[2] + 1)" }
  }
}

if ($next -eq $current) { throw "New version equals current version ($current); nothing to do" }
Write-Host "$current -> $next" -ForegroundColor Cyan

# --- write ---
# Replace only the app.version line, preserving its indentation and trailing comma.
$updated = [regex]::Replace(
  $config,
  $versionLine,
  { param($m) "$($m.Groups[1].Value)$next$($m.Groups[3].Value)" },
  1
)

$versionTs = @"
// GENERATED by scripts/bump-version.ps1 -- do not edit.
// Source of truth is app.version in shell/electrobun.config.ts. Committed (not gitignored) so a
// fresh clone can 'bun run dev' and typecheck without running the bump script first.
export const APP_VERSION = "$next";
"@

if ($PSCmdlet.ShouldProcess("$configPath and $versionTsPath", "write version $next")) {
  # UTF8Encoding($false) = no BOM; a BOM would break Bun's parse of the config. The config's own
  # line endings are left exactly as found -- only the version line changed, so rewriting CRLF to
  # LF (or back) would show up as a whole-file diff on every release.
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($configPath, $updated, $utf8NoBom)
  [System.IO.File]::WriteAllText($versionTsPath, ($versionTs -replace "`r`n", "`n") + "`n", $utf8NoBom)
  Write-Host "  updated shell\electrobun.config.ts" -ForegroundColor DarkGray
  Write-Host "  wrote   core\src\version.ts" -ForegroundColor DarkGray
} else {
  Write-Host "  (WhatIf) no files written" -ForegroundColor DarkGray
}

# The one stdout line, for: $v = & .\scripts\bump-version.ps1 patch
$next
